# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import mesh_pb2 as mesh__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mesh_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeDaemonStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Benchmark = channel.unary_unary(
                '/mesh.NodeDaemon/Benchmark',
                request_serializer=mesh__pb2.BenchmarkRequest.SerializeToString,
                response_deserializer=mesh__pb2.BenchmarkResponse.FromString,
                _registered_method=True)
        self.LoadShard = channel.unary_unary(
                '/mesh.NodeDaemon/LoadShard',
                request_serializer=mesh__pb2.LoadShardRequest.SerializeToString,
                response_deserializer=mesh__pb2.LoadShardResponse.FromString,
                _registered_method=True)
        self.Forward = channel.unary_unary(
                '/mesh.NodeDaemon/Forward',
                request_serializer=mesh__pb2.ForwardRequest.SerializeToString,
                response_deserializer=mesh__pb2.ForwardResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/mesh.NodeDaemon/Heartbeat',
                request_serializer=mesh__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=mesh__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.GetCheckpoint = channel.unary_unary(
                '/mesh.NodeDaemon/GetCheckpoint',
                request_serializer=mesh__pb2.GetCheckpointRequest.SerializeToString,
                response_deserializer=mesh__pb2.GetCheckpointResponse.FromString,
                _registered_method=True)


class NodeDaemonServicer:
    """Missing associated documentation comment in .proto file."""

    def Benchmark(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadShard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Forward(self, request, context):
        """Synchronous recursive relay: a node computes its shard, then (unless it
        holds the exit shard) calls Forward on its next hop and returns
        whatever comes back, with its own timing prepended. The coordinator's
        single call to the entry node's Forward therefore returns the final
        result once the whole chain has run.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCheckpoint(self, request, context):
        """Fault recovery: returns this node's own cached output for a given job,
        so the coordinator can resume a broken chain from the last node that
        finished instead of restarting the whole job from scratch.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeDaemonServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Benchmark': grpc.unary_unary_rpc_method_handler(
                    servicer.Benchmark,
                    request_deserializer=mesh__pb2.BenchmarkRequest.FromString,
                    response_serializer=mesh__pb2.BenchmarkResponse.SerializeToString,
            ),
            'LoadShard': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadShard,
                    request_deserializer=mesh__pb2.LoadShardRequest.FromString,
                    response_serializer=mesh__pb2.LoadShardResponse.SerializeToString,
            ),
            'Forward': grpc.unary_unary_rpc_method_handler(
                    servicer.Forward,
                    request_deserializer=mesh__pb2.ForwardRequest.FromString,
                    response_serializer=mesh__pb2.ForwardResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=mesh__pb2.HeartbeatRequest.FromString,
                    response_serializer=mesh__pb2.HeartbeatResponse.SerializeToString,
            ),
            'GetCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCheckpoint,
                    request_deserializer=mesh__pb2.GetCheckpointRequest.FromString,
                    response_serializer=mesh__pb2.GetCheckpointResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mesh.NodeDaemon', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mesh.NodeDaemon', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeDaemon:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Benchmark(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mesh.NodeDaemon/Benchmark',
            mesh__pb2.BenchmarkRequest.SerializeToString,
            mesh__pb2.BenchmarkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mesh.NodeDaemon/LoadShard',
            mesh__pb2.LoadShardRequest.SerializeToString,
            mesh__pb2.LoadShardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Forward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mesh.NodeDaemon/Forward',
            mesh__pb2.ForwardRequest.SerializeToString,
            mesh__pb2.ForwardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mesh.NodeDaemon/Heartbeat',
            mesh__pb2.HeartbeatRequest.SerializeToString,
            mesh__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mesh.NodeDaemon/GetCheckpoint',
            mesh__pb2.GetCheckpointRequest.SerializeToString,
            mesh__pb2.GetCheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
